### ISSUE TITLE
error installing npm server

### ISSUE THREAD

**Issue by zyptan** [RowanHarley/Slither-Server#24]
> Your environment has been set up for using Node.js 4.5.0 (x64) and npm.

C:\Users\selec>npm install
npm ERR! install Couldn't read dependencies
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "D:\Node\node.exe" "D:\Node\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! path C:\Users\selec\package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! package.json ENOENT: no such file or directory, open 'C:\Users\selec\package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\selec\npm-debug.log

**Comment by zyptan** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'D:\Node\node.exe',
1 verbose cli   'D:\Node\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.15.9
3 info using node@v4.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart Slither-Server@0.0.5
6 info start Slither-Server@0.0.5
7 verbose unsafe-perm in lifecycle true
8 info Slither-Server@0.0.5 Failed to exec start script
9 verbose stack Error: Slither-Server@0.0.5 start: `node ./index.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (D:\Node\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (D:\Node\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:829:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid Slither-Server@0.0.5
11 verbose cwd C:\Users\selec\Downloads\Slither-Server-0.0.5\Slither-Server-0.0.5
12 error Windows_NT 10.0.10586
13 error argv "D:\Node\node.exe" "D:\Node\node_modules\npm\bin\npm-cli.js" "start"
14 error node v4.5.0
15 error npm  v2.15.9
16 error code ELIFECYCLE
17 error Slither-Server@0.0.5 start: `node ./index.js`
17 error Exit status 1
18 error Failed at the Slither-Server@0.0.5 start script 'node ./index.js'.
18 error This is most likely a problem with the Slither-Server package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node ./index.js
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs Slither-Server
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls Slither-Server
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
