### ISSUE TITLE
node index.js Throw Error

### ISSUE THREAD

**Issue by zhu106878723** [RowanHarley/Slither-Server#29]
Error: Cannot find module 'ws'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/zriver-cd/Slither.io/Slither-Server/index.js:7:30)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by AntonUden** [comment]
try npm install
