### ISSUE TITLE
When i try to connect this happens

### ISSUE THREAD

**Issue by Gigabyte918** [RowanHarley/Slither-Server#30]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v7.3.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle Slither-Server@0.0.5~prestart: Slither-Server@0.0.5
6 silly lifecycle Slither-Server@0.0.5~prestart: no script for prestart, continuing
7 info lifecycle Slither-Server@0.0.5~start: Slither-Server@0.0.5
8 verbose lifecycle Slither-Server@0.0.5~start: unsafe-perm in lifecycle true
9 verbose lifecycle Slither-Server@0.0.5~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\A B M\Desktop\Slither-Server-master\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Users\A B M\AppData\Roaming\npm
10 verbose lifecycle Slither-Server@0.0.5~start: CWD: C:\Users\A B M\Desktop\Slither-Server-master
11 silly lifecycle Slither-Server@0.0.5~start: Args: [ '/d /s /c', 'node ./index.js' ]
12 silly lifecycle Slither-Server@0.0.5~start: Returned: code: 1  signal: null
13 info lifecycle Slither-Server@0.0.5~start: Failed to exec start script
14 verbose stack Error: Slither-Server@0.0.5 start: `node ./index.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid Slither-Server@0.0.5
16 verbose cwd C:\Users\A B M\Desktop\Slither-Server-master\src
17 error Windows_NT 6.1.7600
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v7.3.0
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error Slither-Server@0.0.5 start: `node ./index.js`
22 error Exit status 1
23 error Failed at the Slither-Server@0.0.5 start script 'node ./index.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the Slither-Server package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node ./index.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs Slither-Server
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls Slither-Server
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Gigabyte918** [comment]
Sorry for Cut line the are not cutted! HDA
