### ISSUE TITLE
Speed Fix

### ISSUE THREAD

**Issue by GrumpyOet** [RowanHarley/Slither-Server#5]
you have need to change this in the movement.js:

```
var message = require('../utils/message');

var type = 'G'.charCodeAt(0);

exports.build = function(id, x, y) {
    var arr = new Uint8Array(4.8);
    var b = 0;
    b += message.writeInt8(b, arr, 0);
    b += message.writeInt8(b, arr, 0);
    b += message.writeInt8(b, arr, type);
    b += message.writeInt16(b, arr, id);
    b += message.writeInt8(b, arr, x);
    b += message.writeInt8(b, arr, y);
    return arr;
};
```

instead of this:

```
var message = require('../utils/message');

var type = 'G'.charCodeAt(0);

exports.build = function(id, x, y) {
    var arr = new Uint8Array(9);
    var b = 0;
    b += message.writeInt8(b, arr, 0);
    b += message.writeInt8(b, arr, 0);
    b += message.writeInt8(b, arr, type);
    b += message.writeInt16(b, arr, id);
    b += message.writeInt8(b, arr, x);
    b += message.writeInt8(b, arr, y);
    return arr;
};
```

**Comment by GrumpyOet** [comment]
you have need to change the 9 to 4.8

**Comment by RowanHarley** [comment]
I'm away now but I'll fix it as soon as I get home. Thanks!

**Comment by RowanHarley** [comment]
@GrumpyOet When changing 9 to 4.8, the snake is removed from the game. Not sure if this is an error on my side but I'll have a look

**Comment by GrumpyOet** [comment]
Do hou know why the shake get removed from the map?

**Comment by RowanHarley** [comment]
I'm not too sure. The [Slither.io Protocol](https://github.com/ClitherProject/Slither.io-Protocol/blob/master/Protocol.md#type_G_detail) says that there are 6 bytes in the array

**Comment by GrumpyOet** [comment]
but how do we fix it because you only can do 9 not less or more

**Comment by RowanHarley** [comment]
I think we need to fix [position.js](https://github.com/RowanHarley/Slither-Server/blob/master/src/messages/position.js). The buggy movement (and I'd say speed) are because of sending exact co-ordinates. We need to send both (or a mixture of both) to fix the bugs

**Comment by GrumpyOet** [comment]
I think we have neem to change THE position.js to 7 and THE movement.js to 7 or 6

**Comment by GrumpyOet** [comment]
il gonna try that when i am home

**Comment by Mat2095** [comment]
The G packet is 7 bytes long (last index is 6, but index starts at 0), the g packet is 9 bytes long.

**Comment by RowanHarley** [comment]
@Mat2095 The g packet gives me the error: Int16 out of bound. This error comes from [here](https://github.com/RowanHarley/Slither-Server/blob/master/src/utils/message.js)

**Comment by GrumpyOet** [comment]
how they are both Int8

**Comment by GrumpyOet** [comment]
and i don't get a error when i change that but the snake goes a little bit slower

**Comment by RowanHarley** [comment]
I'm talking about [position.js](https://github.com/RowanHarley/Slither-Server/blob/master/src/messages/position.js) not [movement.js](https://github.com/RowanHarley/Slither-Server/blob/master/src/messages/movement.js). I've just updated the code. Uncomment [L126](https://github.com/RowanHarley/Slither-Server/blob/master/index.js#L126) to use position.js.

**Comment by GrumpyOet** [comment]
i think the is something wrong in [L126](https://github.com/RowanHarley/Slither-Server/blob/master/index.js#L126)

**Comment by RowanHarley** [comment]
Don't think there is. Have you uncommented it?

**Comment by GrumpyOet** [comment]
yes en there is no other option to change in the position.js because i tried to change the Uint8Array to every thing from 1 to 20 and nothing of that work

**Comment by GrumpyOet** [comment]
and the error says that's the error is in [L126](https://github.com/RowanHarley/Slither-Server/blob/master/index.js#L126)

**Comment by GrumpyOet** [comment]
the question is why that:

```
    throw new Error('Int16 out of bound.');
      ^

Error: Int16 out of bound.
    at Object.module.exports.writeInt16 (/Users/Luke/Desktop/Slither-Server/src/utils/message.js:20:13)

```

and why that:

`at Object.exports.build (/Users/Luke/Desktop/Slither-Server/src/messages/position.js:12:15)`

right?

**Comment by GrumpyOet** [comment]
no wait i think that the error is in the message.js file (maybe?)

**Comment by RowanHarley** [comment]
It's in position.js, you're right. The number being sent is 144685. Not sure why this number is being sent though

**Comment by RowanHarley** [comment]
Ok, so I think I found the problem. Initially, the body's x and y are sent as Int24's. This means they're gonna be big numbers. position.js is looking for Int8's though. I'm still not sure how I'm gonna fix it but I'll look into it

**Comment by Mat2095** [comment]
Be careful! In the 's' packet the position is an int24, but multiplied by 5. So if the position in the 's' packet is 144685, the snake actually has the coordinates 28937, which fits into an int16. For the 'G' and 'g' packets the coordinates are not multiplied/divided by 5.

**Comment by RowanHarley** [comment]
ok, thanks! I'll check if that fixes it!

**Comment by RowanHarley** [comment]
Ok, after fixing that, the snake barely moves and when it does, it moves in sudden jerks

**Comment by GrumpyOet** [comment]
Rowan what did you change?

**Comment by RowanHarley** [comment]
I changed `broadcast(messages.position.build(conn.id, conn.snake.body.x, conn.snake.body.y));` to `broadcast(messages.position.build(conn.id, (conn.snake.body.x / 5), (conn.snake.body.y / 5)));`

**Comment by Mat2095** [comment]
What client are you using for testing? Does the sudden-movement happen on client side only or also on server side?

**Comment by RowanHarley** [comment]
I'm using the original slither.io client. I only see the jerking client-side only although I have no debug statements that would come up server-side

**Comment by GrumpyOet** [comment]
i tried it to now the snake looks like a retard now

**Comment by Mat2095** [comment]
I don't understand this line:
`conn.snake.body.x += Math.round(Math.cos(conn.snake.direction.angle * 1.44 * Math.PI / 180) * 170);`
- You probably don't have to round here
- What is the measurement of direction.angle? radians? degrees? The formula kindof looks like it should be degrees, but why is it `* 1.44`?
- You definitely need to add the snake-speed to the formula!

If the snake moves too slow on the client side, maybe you didn't send the speed correctly. Typically, the speed is between 5 and 6, lets say 5. The speed is sent in int16, but the client is dividing it by 1000, therefore you need to send 5000.

If you can read/write Java, you can try the server with my client, it should work well for most basic stuff while it only has 1500 to 2000 lines of code.

**Comment by GrumpyOet** [comment]
I think with the
`broadcast(messages.position.build(conn.id, (conn.snake.body.x / 5), (conn.snake.body.y / 5)));`
code

the speed is fine but now we have need to fix the rotation of the snake

**Comment by GrumpyOet** [comment]
for what is this code 
`conn.snake.body.x += Math.round(Math.cos(conn.snake.direction.angle * 1.44 * Math.PI / 180) * 170);`

rotation or something

**Comment by GrumpyOet** [comment]
Rowan i think you must use this code for the next version 0.0.5b2 and fix the retard snake for 0.0.5b2 to
                                                    ......................,.,.,.,.,.,.,.,.,.,..,.,.,.,.,.,   \/
`broadcast(messages.position.build(conn.id, (conn.snake.body.x / 5), (conn.snake.body.y / 5)));`

**Comment by RowanHarley** [comment]
The angle is 0 @Mat2095 (sorry for late reply)

**Comment by Mat2095** [comment]
That's boring :( so the snake can only go to the right?
I meant the measurement, so does it go from 0 to 360 or to 2*PI or something else?

**Comment by GrumpyOet** [comment]
Mat can you make a code for that?

**Comment by GrumpyOet** [comment]
If we can work from here then we only have need to fix rotation of the snake becaus the speed is good

**Comment by GrumpyOet** [comment]
Maybe you can take a look at this:

`https://github.com/whxaxes/slither`

**Comment by GrumpyOet** [comment]
For the rotation

**Comment by Mat2095** [comment]
@GrumpyOet make a code for what?

**Comment by GrumpyOet** [comment]
for rotation of the snake

**Comment by Mat2095** [comment]
I don't speak JS, but this is the general idea:
`deltaAngle = mamu * deltaTime * snake.scang * snake.spang` (`deltaTime` is the time in ms since the last iteration / 8)
Depending on the `snake.dir`:
0: set the `ang` to `wang`
1: subtract `deltaAngle` from `ang`
2: add `deltaAngle` to `ang`
If `wang` is between the old and the new `ang`, set `ang` to `wang` and `dir` to 0

**Comment by RowanHarley** [comment]
There is no snake.scang or snake.spang in my code. Is there a default value for them?

**Comment by GrumpyOet** [comment]
dont ask me I can read JS script but not code it

**Comment by Mat2095** [comment]
`snake.scang = 0.13 + 0.87 * Math.pow((7-snake.sc)/6 , 2)`
`snake.spang = Math.min(snake.speed/spangdv, 1)`
`snake.sc = Math.min(6, 1 + (parts.size-2)/106.0)`

**Comment by GrumpyOet** [comment]
/\ Hè use that code /\

**Comment by RowanHarley** [comment]
@Mat2095 Is that the server-side code or do I need to use the opposites of that?

**Comment by Mat2095** [comment]
You only need opposite code when you modify before/after sending, like you have x in your code, but you send data=10*x, then you have to read it with x=data/10.
So no, this code is the same for server and client (I mean I can't say for sure, the server-code is not public)

**Comment by RowanHarley** [comment]
Just updated the code. Still getting the jerk bug

**Comment by GrumpyOet** [comment]
Can iT be this

`broadcast(messages.movement.build(conn.id, conn.snake.direction.x, conn.snake.direction.y));`

To

`broadcast(messages.movement.build(conn.id, (conn.snake.direction.x / 5), (conn.snake.direction.y / 5)));`

**Comment by RowanHarley** [comment]
no. It's position.js that's the problem

**Comment by GrumpyOet** [comment]
O ok

**Comment by GrumpyOet** [comment]
Maybe because you did / 5 you need to do that on a other conn.snake.body.something /5

**Comment by Mat2095** [comment]
Okay, take a look at the direction-packet ('e'):

You make an Uint8Array sized 7 and write 8 bytes in it. That doesn't work.

You set the first two bytes to 0. This is very wrong! The documentation says "Time since last message from client". I don't know how to calculate the data you need to send here, but you HAVE to find it out (from the client-code) for the server to work. (Take an official server and client, just set these bytes to 0, and the game is broken)

Then you you send the packet-type and id, which is ok.

Next you send the current angle. I doubt it is in the right format, but you still haven't answered my question about that, so I don't know.

Next you send 104 and 1 (You can't, the array is too short). Is this the wanted-angle and speed? So the snake always goes down-left and its speed is always less than 0.06 ?

**Comment by RowanHarley** [comment]
Ok, so about the body x and y, the formula used there is [this](http://gamedev.stackexchange.com/a/18341/68898). The Center_X and Center_Y aren't added as there is no point in adding 0

**Comment by RowanHarley** [comment]
Sorry for the late reply. Ive been busy lately. To answer your question in full.
- Q1: I removed the last byte. Must've missed something there
- Q2: I set the 1st 2 bytes to 0 because I didn't think it would make a difference. If you have any idea where I should be looking, please tell me.
- Q3: ^^
- Q4: The Snake can go any direction. To be honest I don't know why the angle is 104. I changed the last byte to 5.79 although I dont know if that's correct
